title: Nazia Aslam
logo: nazia.jpeg
description: <h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://linkedin.com/in/nazia-aslam-904305100" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="nazia aslam" height="30" width="40" /></a>
<a href="https://medium.com/@naziaaslam_37290" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/medium.svg" alt="@naziaaslam_37290" height="30" width="40" /></a>
</p>
#show_downloads: true
theme: jekyll-theme-minimal
