title: "Nazia Aslam"
logo: nazia.jpeg
description: "Privacy-Preserving Video Anomaly Detection | Computer Vision | Deep Learning"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

author:
  name: "Nazia Aslam"
  avatar: nazia.jpeg
  bio: >
    Postdoc at Aalborg University. Researching privacy-preserving video anomaly detection and ethical AI.
  location: Aalborg, Denmark
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=9uBtJOEAAAAJ&hl=en"
    - label: "GitHub"
      url: "https://github.com/Rabusi"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/nazia-aslam-904305100/"
